### ISSUE TITLE
feature request: add on mouse up function

### ISSUE THREAD

**Issue by robwelan** [mnkhouri/react-circular-slider#2]
I need to update my database when the slider has finished sliding. The onChange event given on the handle feeds to many changes... Can you add an onMouseUp event that fires once the user has finished using the slider? thanks!

**Comment by mnkhouri** [comment]
Hi @robwelan , I've published `0.1.5`, which includes an `onControlEnd` prop that you can register a callback to. I've also added an example to the docs that shows its usage. Please feel free to open another issue if this doesn't meet your needs!
