### ISSUE TITLE
Customize color, stroke-dasharray and circles of the slider

### ISSUE THREAD

**Issue by MaxKoldun** [mnkhouri/react-circular-slider#3]
Can i customize the slider to get the next result ?
![image](https://user-images.githubusercontent.com/26070949/74037073-33d26480-49c6-11ea-97b7-5373db7d57be.png)

**Comment by mnkhouri** [comment]
Hi @MaxKoldun

- Stroke-dasharray: unfortunately this is not possible with this library. Usually, you can apply "stroke-dasharray" to an SVG Arc. However, in this library, I am not using an Arc. Instead, I draw the outer circle, the inner circle, and the two ends of the circle, and I use a Fill. I do this so we can have rounded ends on the tip of the circle:

![image](https://user-images.githubusercontent.com/6535396/74125028-3be6fb80-4ba2-11ea-82d6-d5566da1e59c.png)


- Custom handles for the slider: this has been requested in https://github.com/mnkhouri/react-circular-slider/issues/1, but I have not yet had the time to implement it
