### ISSUE TITLE
Block the slider at both ends

### ISSUE THREAD

**Issue by iAMkVIN-S** [mnkhouri/react-circular-slider#32]
Thank you for your package, very useful.

Currently (although it's a circle and there's not really a "start" and "end") as a user, its obvious that the bottom is 0% and you turn clockwise to move your way to 100%.

We would very much like to be able to stop the circle from infinitely turning and making it difficult to pick 100%.

When turning clockwise it's easy to go from 100% to 0% and vice-versa when going from 0% counter-clockwise it's easy to go to 100%.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/40800721/229623726-e5cde405-a653-4997-a94c-7f9cf2f275a7.gif)

Is there currently a way to block the limits? We tried the `min` and `max` props without any luck!

Cheers

**Comment by mnkhouri** [comment]
Hi @iAMkVIN-S , thanks for the clear description and nice gif!

There's not a built-in way to do this. But you could write some logic into the `onChange` function for the handle, e.g. something like this:

```
const [value1, setValue1] = useState(20);

const setValue1WithLimits = (currentValue: number, newValue: number) {
  if (newValue > (currentValue + 10)) {
    // the handle is snapping too far away! don't do any update
    setValue1(currentValue)
  } else {
    setValue1(newValue)
  }
}

<CircularSlider
  handle1={{
    value: value1,
    onChange: (v) => setValue1WithLimits(value1, v),
  }}
/>
```

That's off the top of my head, it'll probably need some tweaking to work, but I think the idea is sound.

**Comment by iAMkVIN-S** [comment]
Thank you so much for the prompt reply @mnkhouri !

We thought of doing something like this, however, the main issue is that visually, the UI will still snap before getting readjusted and therefore feel "janky".
Specifically in the GIF that I attached, the UI will "flash" quite a bit since the entire circle (yellow) goes to black when the value is say 0, and then back to yellow when our onChange function would kick it back?

Cheers Marc

**Comment by mnkhouri** [comment]
> the UI will "flash" quite a bit since the entire circle (yellow) goes to black when the value is say 0, and then back to yellow when our onChange function would kick it back?

hmm, I don't think that's the case. The UI only updates _as a result_ of calling `onChange`. So if the `onChange` function doesn't set a value (e.g. 100%), that value will never be rendered.

I've uploaded some example code in the commit above ^^ you can see the result at the bottom of the docs page https://marc.khouri.ca/react-circular-slider/ . Try it out and let me know how it goes.

<img width="521" alt="image" src="https://user-images.githubusercontent.com/6535396/229786125-2f4bb81f-1ac4-4d10-8e4f-dc48abc751b9.png">

**Comment by iAMkVIN-S** [comment]
Hey @mnkhouri !

I've looked at your example and it seems to work as intended. We'll look at implamentation later today, but I assume it will behave the same.

You're an absolute legend. Thanks for the quick reply and I'm sure the addition will help others using the package.

**Comment by mnkhouri** [comment]
Welcome, happy to hear that!
