### ISSUE TITLE
onControlFinished not invoked after onTouchEnd

### ISSUE THREAD

**Issue by marekburiak** [mnkhouri/react-circular-slider#33]
If I move the slider using my finger on a mobile device and then lift it, the component won't invoke onControlFinished .

**Comment by mnkhouri** [comment]
good catch on this bug! Will resolve this this week

**Comment by mnkhouri** [comment]
This is fixed now in `master`, I will publish a new version to npm in a few days after #34 is merged.

Thank you for the bug report!
