### ISSUE TITLE
Rangeslider does not work on IOS

### ISSUE THREAD

**Issue by robwelan** [mnkhouri/react-circular-slider#8]
If you use IOS safari / chrome etc, your documentation page does not work (not possible to drag the thumbs). It is essential that this product is cross browser compatible and mobile friendly. https://marc.khouri.ca/react-circular-slider/

**Comment by fireydude** [comment]
this is a duplicate of #4

**Comment by mnkhouri** [comment]
Closing as dupe of #4 , thanks @fireydude

**Comment by mnkhouri** [comment]
Touch support published in v0.2.0!
